#!/usr/bin/env python

import sys
import urllib

def parse_query_string(string):
    try:
        params =  string.split("?")[1].split("&")
    except IndexError, e:
        raise IndexError("Not a valid url")

    return params

def format(args):
    return urllib.unquote(str(tuple(args.split("=")))).decode("utf-8")

if __name__ == "__main__":
    for p in parse_query_string(sys.argv[1]):
        sys.stdout.write((format(p)))
        sys.stdout.write("\n")
